version: '3.3'

services:
  dotnet-api:
    container_name: dotnet_api
    image: http-service/dotnet-api
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - './server:/app'
  sqlserver:
    container_name: sqlserver
    build:
      context: ./
      dockerfile: ./images/db.dockerfile
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "BigPassw0rd"
    volumes:
      - ./data/mssql:/var/opt/mssql3
    ports:
      - '1433:1433'
    expose:
      - 1433